#### Loading cleaned datasets

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ECB API data
df = pd.read_csv('inflation_clean.csv')

# Eurostat API
df2 = pd.read_csv('interest_clean.csv')


df.head(25)

       date country  inflation
0   2015-01      DE       -0.5
1   2015-02      DE       -0.2
2   2015-03      DE        0.3
3   2015-04      DE        1.0
4   2015-05      DE        1.6
5   2015-06      DE        1.1
6   2015-07      DE        1.3
7   2015-08      DE        1.1
8   2015-09      DE        0.8
9   2015-10      DE        1.2
10  2015-11      DE        0.2
11  2015-12      DE        0.2
12  2016-01      DE        0.4
13  2016-02      DE       -0.1
14  2016-03      DE        0.1
15  2016-04      DE       -0.3
16  2016-05      DE       -0.1
17  2016-06      DE        0.1
18  2016-07      DE        0.3
19  2016-08      DE        0.3
20  2016-09      DE        0.6
21  2016-10      DE        0.7
22  2016-11      DE        0.8
23  2016-12      DE        1.6
24  2017-01      DE        1.7

In [2]:
df2.head()

      date  interest
0  2015-12     -0.30
1  2016-03     -0.40
2  2019-09     -0.50
3  2022-07      0.00
4  2022-09      0.75

---

In [3]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df2["date"] = pd.to_datetime(df2["date"], errors="coerce")

In [4]:
df2["interest"] = pd.to_numeric(df2["interest"], errors="coerce")

# Keep only what we need
df2 = df2[["date", "interest"]]

# Remove the duplicates
df2 = df2.drop_duplicates(subset=["date"])
df = df.drop_duplicates(subset=["country", "date"])


### Merging the datasets via date

In [5]:
# Making sure the date format matches each dataset
df['date'] = pd.to_datetime(df['date']).dt.to_period('M').astype(str)
df2['date'] = pd.to_datetime(df2['date']).dt.to_period('M').astype(str)

In [6]:
# Merge the two datsets
df_merged = pd.merge(df,df2, on='date', how='left')

# Sort the values
df_merged = df_merged.sort_values(['country', 'date'])

In [7]:
df_merged

        date country  inflation  interest
0    2015-01      DE       -0.5       NaN
1    2015-02      DE       -0.2       NaN
2    2015-03      DE        0.3       NaN
3    2015-04      DE        1.0       NaN
4    2015-05      DE        1.6       NaN
..       ...     ...        ...       ...
427  2023-08      IT        5.5      3.75
428  2023-09      IT        5.6      4.00
429  2023-10      IT        1.8       NaN
430  2023-11      IT        0.6       NaN
431  2023-12      IT        0.5       NaN

[432 rows x 4 columns]

In [8]:
# Filling in the Nan values
df_merged = df_merged.sort_values(["country", "date"])

df_merged["interest"] = df_merged["interest"].ffill().bfill()

In [9]:
df_merged.tail()

        date country  inflation  interest
427  2023-08      IT        5.5      3.75
428  2023-09      IT        5.6      4.00
429  2023-10      IT        1.8      4.00
430  2023-11      IT        0.6      4.00
431  2023-12      IT        0.5      4.00

In [10]:
df_merged.shape

(432, 4)

In [14]:
df_merged['country'].unique()

array(['DE', 'ES', 'FR', 'IT'], dtype=object)

In [11]:
print(df_merged[df_merged["inflation"].isna()].head(20))

Empty DataFrame
Columns: [date, country, inflation, interest]
Index: []

In [12]:
print(df_merged[df_merged["inflation"].isna()]["date"].unique())

[]

In [13]:
df_merged.head(50)

       date country  inflation  interest
0   2015-01      DE       -0.5      -0.3
1   2015-02      DE       -0.2      -0.3
2   2015-03      DE        0.3      -0.3
3   2015-04      DE        1.0      -0.3
4   2015-05      DE        1.6      -0.3
5   2015-06      DE        1.1      -0.3
6   2015-07      DE        1.3      -0.3
7   2015-08      DE        1.1      -0.3
8   2015-09      DE        0.8      -0.3
9   2015-10      DE        1.2      -0.3
10  2015-11      DE        0.2      -0.3
11  2015-12      DE        0.2      -0.3
12  2016-01      DE        0.4      -0.3
13  2016-02      DE       -0.1      -0.3
14  2016-03      DE        0.1      -0.4
15  2016-04      DE       -0.3      -0.4
16  2016-05      DE       -0.1      -0.4
17  2016-06      DE        0.1      -0.4
18  2016-07      DE        0.3      -0.4
19  2016-08      DE        0.3      -0.4
20  2016-09      DE        0.6      -0.4
21  2016-10      DE        0.7      -0.4
22  2016-11      DE        0.8      -0.4
23  2016-12      DE        1.6      -0.4
24  2017-01      DE        1.7      -0.4
25  2017-02      DE        2.1      -0.4
26  2017-03      DE        1.5      -0.4
27  2017-04      DE        2.0      -0.4
28  2017-05      DE        1.3      -0.4
29  2017-06      DE        1.7      -0.4
30  2017-07      DE        1.7      -0.4
31  2017-08      DE        1.9      -0.4
32  2017-09      DE        1.9      -0.4
33  2017-10      DE        1.5      -0.4
34  2017-11      DE        1.7      -0.4
35  2017-12      DE        1.5      -0.4
36  2018-01      DE        1.5      -0.4
37  2018-02      DE        1.2      -0.4
38  2018-03      DE        1.7      -0.4
39  2018-04      DE        1.3      -0.4
40  2018-05      DE        2.5      -0.4
41  2018-06      DE        2.1      -0.4
42  2018-07      DE        2.2      -0.4
43  2018-08      DE        2.1      -0.4
44  2018-09      DE        2.2      -0.4
45  2018-10      DE        2.6      -0.4
46  2018-11      DE        2.2      -0.4
47  2018-12      DE        1.7      -0.4
48  2019-01      DE        1.7      -0.4
49  2019-02      DE        1.7      -0.4